- src/views/TooltipsView.vue
Fix a document issue: v-badge -> v-tooltip
> Fix a document issue: v-badge -> v-tooltip

- src/views/SidebarView.vue
ref https://github.com/vuetifyjs/vuetify/issues/145
> Doc for Sidebar:disable-route-watcher

- public/examples/layouts/2.html
Struggled to get this example to work; it seems to work on the docs site but wouldn't work locally. I think this is just a missed change from 0.8.8?
> minor correction to updated toolbar example #2

- src/views/ThemeView.vue
> Complete Path

- public/examples/layouts/4.html
- left-fixed-sidebar included twice
- v-sidebar needs fixed prop
> Fixing errors in example layout 4

- examples/dialogs/3.vue
Fix for fullscreen dialog example missing light theme [http://i.imgur.com/JRFkhVU.png](http://i.imgur.com/JRFkhVU.png)
> Dialogs fullscreen example toolbar theme -> light

- pages/PickersView.vue
Related to vuetifyjs/vuetify#622
> Added firstDayOfWeek prop to API section

- examples/pickers/10.vue
- pages/PickersView.vue
Added doc example for allowed times (https://github.com/vuetifyjs/vuetify/issues/594)
> Extend allowed dates to time pickers

- examples/menus/4.vue
- examples/menus/5.vue
- examples/menus/6.vue
- pages/MenusView.vue
Related to vuetifyjs/vuetify#706
> Menu without activator

- examples/tables/7.vue
- pages/DatatablesView.vue
Related to https://github.com/vuetifyjs/vuetify/pull/737
> Datatable slots

- examples/tables/2.vue
- examples/tables/4.vue
- examples/tables/5.vue
- examples/tables/7.vue
- examples/tables/8.vue
- pages/DatatablesView.vue
Related to https://github.com/vuetifyjs/vuetify/issues/731
> added examples for headers/headerCell slots

- examples/sliders/2.vue
- examples/sliders/5.vue
- pages/SliderView.vue
Related to https://github.com/vuetifyjs/vuetify/issues/219
> Updated slider examples

- examples/pickers/13.vue
- pages/PickersView.vue
Related to https://github.com/vuetifyjs/vuetify/issues/757
> added datepicker international example

- examples/badges/4.vue
- pages/BadgesView.vue
Related to https://github.com/vuetifyjs/vuetify/issues/796
> Added badge visibility example

- components/ComponentView.vue
- examples/tabs/1.vue
- examples/tabs/2.vue
- examples/tabs/3.vue
- examples/tabs/4.vue
- examples/tabs/5.vue
- examples/tabs/8.vue
- examples/tabs/9.vue
- pages/TabsView.vue
Updated tabs examples, related to https://github.com/vuetifyjs/vuetify/issues/791
> Updated tab examples

- examples/selects/5.vue
- examples/selects/6.vue
- examples/selects/7.vue
- pages/SelectView.vue
- Added example and api for autocomplete
- Fixed minor typo for Nebraska, NE (was NB)
> Updated v-select

- pages/QuickStartView.vue
PWA stands for progressive web app
> Fixed typo of PWA

- pages/QuickStartView.vue
BTW the vue cli template uses the right section:
https://github.com/vuetifyjs/webpack-advanced/blob/master/template/package.json#L19
> Vuetify isn't a development dependency

- pages/ListsView.vue
Hope this is the right place to fix the link.
PS: I was not able to perform a local build. There is no guide on how to create a local build, it might be a good idea to add a note to the readme. `npm run dev` almost froze my computer (virtual).
> Fixed github link to the list component

- pages/MenusView.vue
https://github.com/vuetifyjs/vuetify/pull/1163/commits/a2f179a92e69f7ba3428998e695c7c156b684332
> Update documentation to include new events

- pages/HomeView.vue
I missed that one. Closes #163
> Fix link in footer

- examples/forms/2.vue
- pages/FormsView.vue
> Document v-form validation changes

- pages/PickersView.vue
https://github.com/vuetifyjs/vuetify/issues/1651
> update datepicker docs for #1651

- pages/DatatablesView.vue
docs for https://github.com/vuetifyjs/vuetify/issues/1246
> data-table/must-sort

- pages/DatatablesView.vue
I also removed the formatting since it won't show up in the HTML.
> Corrected the default filter function value

- pages/MenusView.vue
docs for https://github.com/vuetifyjs/vuetify/pull/1796
> open-delay/close-delay

- pages/ProgressView.vue
https://github.com/vuetifyjs/vuetify/pull/1780
> v-progress-circular/colorable

- examples/pickers/3.vue
Specs:
https://material.io/guidelines/components/pickers.html
https://material.io/guidelines/components/dialogs.html#dialogs-full-screen-dialogs
> Update Date Picker example with the Material specs

- examples/pickers/6.vue
Specs:
https://material.io/guidelines/components/pickers.html#pickers-time-pickers
> Update Time Picker example with Material specs

- components/ComponentParameters.vue
- components/ComponentView.vue
Pretty basic, but should help clean things up a bit:
Doesn't work at all on functional components, and has a few false positives with others, but it'll do.
> Show difference between actual and documented props

- components/ComponentExample.vue
- components/ComponentView.vue
- layouts/Default.vue
- package-lock.json
- package.json
- router/index.js
- yarn.lock
I also fixed the scrolling issues with anchors on initial load. 
Resolves #175
> Add links to component examples

- examples/carousel/hide-delimiters.vue
- pages/CarouselView.vue
Doc update for https://github.com/vuetifyjs/vuetify/pull/2190
> feat(v-carousel): updated examples to reflect changes in component

- pages/SliderView.vue
https://github.com/vuetifyjs/vuetify/pull/2242
> SliderView API update

- pages/PickersView.vue
https://github.com/vuetifyjs/vuetify/pull/2109
> DatePicker API update

- pages/TooltipsView.vue
https://github.com/vuetifyjs/vuetify/pull/2164
> TooltipsView - disabled prop

- pages/PickersView.vue
https://github.com/vuetifyjs/vuetify/pull/2199
> Pickers/colorable API

- pages/ToolbarsView.vue
https://github.com/vuetifyjs/vuetify/pull/2188
> SystemBar - absolute/fixed props

- pages/DatatablesView.vue
https://github.com/vuetifyjs/vuetify/pull/2252
> DataTable - no-data/no-results slots

- examples/tables/noData.vue
- pages/DatatablesView.vue
https://github.com/vuetifyjs/vuetify/pull/2252
> data-table no-data slot example

- examples/cards/horizontal.vue
- examples/layouts/baseline-flipped.vue
- examples/layouts/baseline.vue
- examples/layouts/complex.vue
- examples/layouts/dark.vue
- examples/layouts/google-contacts.vue
- examples/layouts/google-keep.vue
- examples/layouts/google-youtube.vue
- examples/layouts/sandbox.vue
- examples/text-fields/character-counter.vue
- pages/LayoutsView.vue
- pages/QuickStartView.vue
- pages/SSRView.vue
- themes/blog-starter/index.html
- themes/parallax-starter/index.html
https://github.com/vuetifyjs/vuetify/pull/2298
> removed main tag

- pages/ExpansionPanelView.vue
> Add 'actions' slot description

- pages/GridView.vue
This should stop the Github link from breaking.
> Change "component: 'grid'" to "component: 'VGrid'"

- pages/FormsView.vue
I think some other edit links do not work either.
> Fixing the edit button

- themes/blog-starter/index.html
Change tags `<a></a>` for component `<v-btn></v-btn>`
> Change template blog starter

- examples/alerts/outline.vue
- pages/AlertsView.vue
The docs update for this PR: https://github.com/vuetifyjs/vuetify/pull/2336
I basically copied most of the wording from the Button component, but I'm open to suggestions to improve it :)
> Add example for Alert component's outline prop

- pages/DatatablesView.vue
> updated item-key prop type

- layouts/Default.vue
- pages/GridView.vue
> Remove references to $vuetify.load()

- pages/SelectView.vue
https://github.com/vuetifyjs/vuetify/pull/2375
> content-class for v-select

- pages/LayoutsView.vue
"Customed" isn't a word. Changing it to customized.
> Simple spelling/grammar fix

- pages/DatatablesView.vue
Quick docs for https://github.com/vuetifyjs/vuetify/pull/2368
> Add `disable-initial-sort` prop to DataTable docs
